version: "3.9"
services:
  postgres:
    image: 'postgres:14.2'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: hvvvd11
      POSTGRES_PASSWORD: password
      POSTGRES_DB: amazon_clone
    volumes:
      - ./db-data/postgres/:/var/lib/postgresql/data/
    restart: always
